apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ojvrhkqy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ojvrhkqy:d2aa5a501c119474a13bb1875a2b5ce027540ec5@sha256:bfaa5763a1e2f29397ff6ba4fee58fb9182bb91a0c942f37be00d630b8d03550
          name: container-image
